### PR TITLE
Mobile ui fixes

### PR DESCRIPTION
**Pull request by ctaylo21**
I made a V1 pass at cleaning up the UI on mobile. Everything should fit correctly now on a mobile device but still look the same as it currently does on desktop.

### CODE REVIEW

**Comment by ctaylo21** [comment]
image
image

Screenshots of new UI

**Comment by ctaylo21** [comment]
@nindalf Hello! Any chance you could take a look at this? Thanks!

**Comment by nindalf** [comment]
This looks so great! Thanks so much @ctaylo21!

Let me test locally today and merge it if looks good.

**Comment by nindalf** [comment]
Thanks @ctaylo21 !

**Pull request merged**
